### ISSUE TITLE
TODO list before the final submit of the PDC metadata records:

### ISSUE THREAD

**Issue by JessyBarrette** [cioos-siooc/pdc-metadata-conversion#1]
This is the things that needs to be done before completing the PDC to CIOOS metadata record converstion:

- [ ] Retrieve CIOOS EOV by using the PDC keywords
- [ ] Assign a default license: https://creativecommons.org/licenses/by/4.0/?
- [ ] Define `Data Owner` which is a required role
- [ ] Apply automated french translation
- [ ] Filter which records should be migrated to the Amundsen Science Catalog
- [ ] Assign Metadata Custodian and Distributor to Amundsen science
- [ ] Remove PDC from contacts
- [ ] Missing CCINs #2

**Comment by JessyBarrette** [comment]
A first draft of the different metadata records is now available here:

https://cioos-siooc.github.io/metadata-entry-form/#/en/amundsen/reviewer
